version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: openfinanceDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
